### ISSUE TITLE
Support for other extensions

### ISSUE THREAD

**Issue by danielfalk** [moll/vim-node#16]
With the coming of ES6, as well as server-side react, there are a few more extensions that it would be good if vim-node would recognize:  *.es, *.es6, *.jsx

**Comment by moll** [comment]
Hey again!

I took a 6 hour nap during the night and came up with another approach to solving both your request and possibly others. How would you feel about the following and would you mind giving it a spin? :-)

In short, Vim has the `'suffixesadd'` option to support arbitrary extension autocompletion. When initializing, Node.vim adds `.js` and `.json`, the only extensions Node.js supports by default, to that.

How about rather than extending the default list for everyone when it might only apply to some, we'll direct people just to add what they need to `suffixesadd`?

```vim
autocmd User Node set suffixesadd+=.es,.es6,.jxs
```

**Comment by danielfalk** [comment]
That works.  Guess the code change is not needed then.

**Comment by moll** [comment]
Superb. Thank you again!
I'll reopen this if you don't mind just to remind me to add a note about this in the README!

**Comment by moll** [comment]
I ended up adding `.es` and `.jsx` to `&suffixesadd` anyways. :-)
